version: '3'

services:
    db:
        image: mysql
        volumes:
            - db_data:/var/lib/mysql
        restart: unless-stopped
        ports:
            - 33060:3306
        environment:
            MYSQL_ROOT_PASSWORD: sfm
            MYSQL_DATABASE: sfm
            MYSQL_USER: sfm
            MYSQL_PASSWORD: sfm
    phpmyadmin:
        image: phpmyadmin/phpmyadmin
        restart: unless-stopped
        depends_on:
            - db
        ports:
            - 8181:80
        environment:
            MYSQL_USER: sfm
            MYSQL_PASSWORD: sfm
            MYSQL_ROOT_PASSWORD: sfm
volumes:
    db_data:
