version: '2'

services:
    db:
        image: mysql
        volumes:
            - db_data:/var/lib/mysql
        restart: always
        ports:
            - 33060:3306
        environment:
            MYSQL_ROOT_PASSWORD: 
            MYSQL_DATABASE: 
            MYSQL_USER: 
            MYSQL_PASSWORD: 
    phpmyadmin:
        image: phpmyadmin/phpmyadmin
        restart: always
        depends_on:
            - db
        ports:
            - 8181:80
        environment:
            PMA_ARBITRARY: 1
            MYSQL_USER: 
            MYSQL_PASSWORD: 
            MYSQL_ROOT_PASSWORD: 
volumes:
    db_data:
